### ISSUE TITLE
Configurable spacing for jsbeautifier?

### ISSUE THREAD

**Issue by KyleKing** [hukkin/mdformat-web#2]
Would it be possible to add a configurable indent to the pre-commit hook for 2-space indents?

**Comment by hukkin** [comment]
Hey, thanks for the issue!

The code formatter plugin API doesn't make this very easy currently. Code formatter plugins don't have access to CLI options or `.mdformat.toml` options. We could use the code fence info string here, e.g.

````markdown
```javascript indent=4
console.log("foo")
```
````

But this probably isn't what most people would want as they'd need to add the options to each code fence separately.

Maybe we should consider giving code formatter plugins access to options, although sadly that is a breaking change.

**Comment by KyleKing** [comment]
Okay, that is too bad. Thanks for looking into it!

**Comment by codingjoe** [comment]
It'd be cool to somehow read this from the `.editorconfig` file. I know that `jsbeautifier` supports it. @hukkin is there any good way to pass it, especially via pre-commit?
